runtime: nodejs10 # For Node.js 8, use runtime: nodejs8

instance_class: F1

env_variables:
  DATABASE_HOST: '/cloudsql/endurostats:europe-west1:endurostats2'
  DATABASE_USER: "endurostats"
  DATABASE_PASSWORD: "OYFsYz2Yhl8cC0f7TJX2ayhjEgn0fWYWjQlzZ3P9"
  DATABASE: "endurostats"
  NODE_ENV: "production"

handlers:
- url: /.*
  script: auto
  secure: always

beta_settings:
  cloud_sql_instances: 'endurostats:europe-west1:endurostats2'
